name: flutter_foods
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  convex_bottom_bar: ^3.2.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_rating_bar: ^4.0.1
  flutter_tabler_icons: ^1.43.0
  flutter_zoom_drawer: ^3.2.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.0.0
  shared_preferences: ^2.3.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
