name: flutter_foods
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  convex_bottom_bar: ^3.2.0
  permission_handler: ^10.2.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  flutter_dotenv: ^5.0.2
  flutter_rating_bar: ^4.0.1
  flutter_tabler_icons: ^1.43.0
  flutter_zoom_drawer: ^3.2.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  location: ^7.0.1
  latlong2: ^0.9.1
  open_street_map_search_and_pick: ^0.1.1
  cached_network_image: ^3.2.3 
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
